apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sock-shop-prod
    networking.gke.io/managed-certificates: sockshop.kapicorp.com
  labels:
    name: global
  name: global
  namespace: prod-sockshop
spec:
  backend:
    service:
      name: frontend
      port: 80
