apiVersion: v1
data:
  mysql-password: OVUxaHYyenpNc091VzJRRzVJQTJlQW5ueUxUTkhHTUlfRmRuMjM1T3hqZw==
  mysql-root-password: eENYeVRtUHlnbHVHNHdiNzZSaVJPb1BvN2Raa1JoU3Y=
kind: Secret
metadata:
  labels:
    name: mysql
  name: mysql-ffbba340
  namespace: examples
type: Opaque
