apiVersion: v1
data:
  mongodb-root-password: YnRpUEpZZDV6aU5OdnQ4cFVJaVI4T2R6YV84NEVVbWtJX3lrMEJrZlJuaw==
kind: Secret
metadata:
  labels:
    name: pritunl-mongo
  name: pritunl-mongo
  namespace: gke-pvm-killer
type: Opaque
