apiVersion: v1
data:
  service_account_file: J1hoJ3NqNMJskxoIeR7isW6fJb9Ju_XH253k1sXn9PY
kind: Secret
metadata:
  labels:
    name: postgres-proxy
  name: postgres-proxy
  namespace: echo-server
type: Opaque
