apiVersion: v1
data:
  mysql-password: UG05UVdwUFh2ODR6QlQ4ZURwMWRZRUNSd1M1UU00OGtJR0djcTg0dkg0VQ==
  mysql-root-password: dHJNWmY0bnVyaWZFNFdPdzhheVNiVVlVY1hhTWQxUEg=
kind: Secret
metadata:
  labels:
    name: mysql
  name: mysql
  namespace: global
type: Opaque
